### ISSUE TITLE
Idaho Statistics Problems Moved/Not Found in Browser

### ISSUE THREAD

**Issue by thatchermo** [openwebwork/webwork-open-problem-library#1180]
Two problems from the College of Idaho statistics collection appear to have been moved, but their entries in the database that powers the OPL problem browser hasn't been updated.

In WeBWork 2.15 a few years ago, they were at

Library/CollegeOfIdaho/setStatistics_Ch04ScatterplotsAndCorrelation/04Stats_06_ScatterCorrelation/04Stats_06_ScatterCorrelation.pg

and 

Library/CollegeOfIdaho/setStatistics_Ch04ScatterplotsAndCorrelation/04Stats_02_ScatterCorrelation/04Stats_02_ScatterCorrelation.pg

but they appear to have been moved to 

Library/CollegeOfIdaho/setStatistics_Ch04ScatterplotsAndCorrelation/04Stats_06_ScatterCorrelation.pg

and

Library/CollegeOfIdaho/setStatistics_Ch04ScatterplotsAndCorrelation/04Stats_02_ScatterCorrelation.pg

The problem browser still looks for them at the old address and give a "No such file or file was empty!" error.

I haven't looked extensively, but it might be good to see if any other Idaho problems had the same thing happen. Thanks for your work on this wonderful resource!

Edit: Should mention this is in 2.19, updated at the beginning of August.

**Comment by dlglin** [comment]
Did you run `OPL-update` to update the OPL?  That script updates both the Library folders and the database used by the Library Browser.

**Comment by dlglin** [comment]
No worries.  The instructions are not super clear on such things.
