### ISSUE TITLE
Library/Michigan/Chap19Sec2/Q27.pg: mistake in the last step of the solution

### ISSUE THREAD

**Issue by sean-fitzpatrick** [openwebwork/webwork-open-problem-library#1214]
Problem Seed: 1895

The final step of the solution for this problem does the integral of 1+cos(theta)sin(theta) from 0 to pi/2, and obtains the result pi/2+1.

But the second term should be 1/2.

The programmed answer is correct; it is just the solution where there is a mistake.

**Comment by gajennings** [comment]
It's fixed now.
