### ISSUE TITLE
Bug in Math Problem

### ISSUE THREAD

**Issue by mwytang** [openwebwork/webwork-open-problem-library#124]
The math problem is: webwork-open-problem-library/OpenProblemLibrary/WHFreeman/Rogawski_Calculus_Early_Transcendentals_Second_Edition/13_Calculus_of_Vector-Valued_Functions/13.1_Vector-Valued_Functions/13.1.30.pg at line 36

Variable $a1 does not anywhere else in the file. We assume it should be variable $a.

Thanks.

**Comment by jwj61** [comment]
Fixed as suggested
