### ISSUE TITLE
Sign error on line 103

### ISSUE THREAD

**Issue by cameron-gagnon** [openwebwork/webwork-open-problem-library#138]
The problem in question is: https://github.com/openwebwork/webwork-open-problem-library/blob/master/OpenProblemLibrary/Michigan/Chap8Sec2/Q19.pg

I believe there is a sign error on line 103 where it states the upper bound is x = -1. When it should be x = 1. In the end it should read form line 102 - 103 as "The lower bound is x = -1 and the upper bound is x = 1."

**Comment by paultpearson** [comment]
Thanks.  It is now fixed on GitHub (a git pull should download the changes for you).
