### ISSUE TITLE
Mathematical issue with a problem in the library 

### ISSUE THREAD

**Issue by jbryanvancouver** [openwebwork/webwork-open-problem-library#147]
The file for the problem is

'[TMPL]/Library/WHFreeman/Rogawski_Calculus_Early_Transcendentals_Second_Edition/16_Line_and_Surface_Integrals/16.2_Line_Integrals/16.2.41.pg'

The answer for all three plots should be zero, whereas the solutions show one of the graphs as having a negative integral with the following (bogus) argument:

"For the vector field below the contribution of the negative tangential component appear to dominate over the positive contribution, hence the line integral is negative."

In fact, if one looks closely at the plot, the vector field is clearly intended to be of the form <f(x),g(y)> and is hence conservative and hence the integral around the closed loop should be zero. The reasoning given in the "solution" is bogus. In fact, the integral is positive for about 3/4ths of the way around the circle, so it is not at all clear that the negative contributions dominate the positive contributions.

**Comment by jwj61** [comment]
Changed answer to 0, and altered explanation.
