### ISSUE TITLE
Problem Incorrect

### ISSUE THREAD

**Issue by bpaynter** [openwebwork/webwork-open-problem-library#160]
It may just be me, but I believe that there is a problem with question:
Library/CSUOhio/appletDemonstrationProblems/LabelingPointsCustom.pg
I think that it has the wrong answers coded. Most likely a cut/paste error.

**Comment by bpaynter** [comment]
Proposed changes to the file

**Comment by jwj61** [comment]
I am confused by this.  It says it is proposing changes, but is closing the report at the same time without the proposed changes.  I will not worry about it unless it is reopened.
