### ISSUE TITLE
Ambiguous use of ${BBOLD} resolved to $BBOLD at (eval 2193) line 7.

### ISSUE THREAD

**Issue by bldewolf** [openwebwork/webwork-open-problem-library#172]
Hello, recently updated to a system with Perl 5.18.2 and it complains about style more.  It looks like there's some problems causing these sorts of lines to appear in the apache log:

    Ambiguous use of ${BBOLD} resolved to $BBOLD at (eval 2193) line 7.
    Ambiguous use of ${BBOLD} resolved to $BBOLD at (eval 2193) line 14.

From perldiag:

>Ambiguous use of %c{%s} resolved to %c%s
>
>(W ambiguous) You wrote something like "@{foo}", which might be asking for the
>variable @foo, or it might be calling a function named foo, and dereferencing
>it as an array reference.  If you wanted the variable, you can just write
>@foo.  If you wanted to call the function, write "@{foo()}" ... or you could
>just not have a variable and a function with the same name, and save yourself
>a lot of trouble.

It looks like a lot of problems reference `${BBOLD}`.  Is there a simple way to remove the ambiguity?

**Comment by paultpearson** [comment]
Could you provide an example of a problem that does this?  Also, ${BBOLD} is useful.  For instance, ${BBOLD}some text${EBOLD} works but $BBOLDsome text$EBOLD fails because it is looking for a nonexistent variable named $BBOLDsome.  An alternative is $BBOLD some text $EBOLD, which should work well but does not always do what the problem author intended with spacing.

**Comment by jwj61** [comment]
Interesting.  I can't seem to trigger it, and I have perl 5.18.2.

It may be possible to fix this without changing the problems, which would be good since as Paul points out, it serves a purpose, and seems to be the "official perl way" of accomplishing its job.

**Comment by bldewolf** [comment]
I looked through one of our current courses and found an example problem, [FortLewis/Calc1/05-02-Definite-integral/HGM5-05-02-Definite-integral-29.pg](https://github.com/openwebwork/webwork-open-problem-library/blob/master/OpenProblemLibrary/FortLewis/Calc1/05-02-Definite-integral/HGM5-05-02-Definite-integral-29.pg)

My understanding now is that the ambiguity is from `${BBOLD}` used outside of a string.  In a string, `${BBOLD}` is unambiguous.  Outside a string, Perl has to decide whether the author wants the value of `${BBOLD()}` or `$BBOLD`, since both the variable and the function exist.

I've modified this problem on my system to use $BBOLD and it works without complaints now.

**Comment by paultpearson** [comment]
I had no idea this was an issue.  I have replaced "${BBOLD}" by "$BBOLD " (note the space at the end) and done similar things for EBOLD, BITALIC, EITALIC, and PAR for the .pg files in the OPL directories for FortLewis, LoyolaChicago, MiamiUOhio, Hope, and Rochester where I have done most of my problem authoring and editing.

John Jones: should these substitutions be done for the entire OPL?

**Comment by mgage** [comment]
Does this behavior persist in later versions of perl.  It almost looks like a perl bug to me.
using something like ${DOLLAR} is useful if you want no space after the dollar sign and you are using it in string.  It will have the same issue.

Having BBOLD() and $BBOLD both defined was a cautious design decision long ago but I can't recall ever using BBOLD() so it was probably unnecessary.

My understanding is that {BBOLD} selects the glob and then the sigil in front selects which part of that glob you will use  ${BBOLD} should select the scalar part,  I would have thought that &{BBOLD}() would
select the subroutine part.  It's possible things are changing but it's also possible that this was a temporary oversight in perl's evolution.  It's happened before.

**Comment by jwj61** [comment]
I don't think we should make a generic substitution.  As Paul pointed out earlier, there are times the author wanted ${BBOLD} (or Mike with ${DOLLAR}).  Almost every use will be in strings (e.g., between BEGIN_TEXT/END_TEXT) and those are fine.  That is probably why I could not replicate the bug even though I have the same version of perl -- I was looking at a different problem.  On that problem, I get the bug, and was able to fix the problem easily.

For now, I suggest adjusting only the offending ones as they are encountered.  For example, on the problem cited above, it is an easy switch.

The question remains whether to undo Paul's replacements by just unwinding the git commit record.

**Comment by jwj61** [comment]
For the reasons from my last comment, I think it is better to treat these as bugs on a case by case basis.  Even when it occurs, the only downside is an entry in the apache error.log -- it is not visible to users or students.

So, I just undid the replacements Paul did, and fixed the one file mentioned above.  If anyone sees another file triggering this, by all means submit a bug report on the problem.
