### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by NeilHanlon** [openwebwork/webwork-open-problem-library#210]
The docs at http://webwork.maa.org/wiki/Open_Problem_Library#.VmhnXXM4l8E say to update the OPL, you need to ```git pull``` and then run a ```./OPL-update``` -- but this script does not exist.

Does anything need to happen besides just pulling the repo?

**Comment by jwj61** [comment]
The script is part of webwork2, in .../webwork2/bin .

**Comment by NeilHanlon** [comment]
Awesome. Thanks.

Should I file something against webwork to update the website?

**Comment by mgage** [comment]
Sure.  Be specific about the page (URL and place on the page) where the confusion occurs.
