### ISSUE TITLE
Typo in problem Lebl-1-1-09.pg

### ISSUE THREAD

**Issue by chdsbd** [openwebwork/webwork-open-problem-library#257]
There is a typo [here](https://github.com/openwebwork/webwork-open-problem-library/blob/fb0828956c79477d86c9950ea91bac134411aa88/OpenProblemLibrary/FortLewis/DiffEq/1-First-order/01-Integrals-as-solutions/Lebl-1-1-09.pg#L57). It says `is is`, when it should say `it is`.

**Comment by paultpearson** [comment]
Thanks for pointing this out.  It's now fixed on github.
