### ISSUE TITLE
question about "horizontal line" coding

### ISSUE THREAD

**Issue by ES2660** [openwebwork/webwork-open-problem-library#289]
The coding of this problems gives away the fact that horizontal line have equations of the form y=b by displaying y= before an empty box. How can it be fixed to that the students have to type the whole answer y=b not just b. 
 webwork-open-problem-library/OpenProblemLibrary/Utah/Business_Algebra/set6_Linear_Equations_and_Functions/p11.pg

**Comment by paultpearson** [comment]
Using MathObjects, this is easy.  Something like this should work:

http://webwork.maa.org/wiki/EquationsDefiningFunctions

(You don't need the parserAssignment stuff to do what you want.)

**Comment by jwj61** [comment]
Paul's response seems to cover it, so closing the issue

**Comment by dlglin** [comment]
Since this is the equation of a line, the Implicit Plane context has more meaningful error messages:
http://webwork.maa.org/wiki/ImplicitPlane
