### ISSUE TITLE
image

### ISSUE THREAD

**Issue by ES2660** [openwebwork/webwork-open-problem-library#290]
The graph doesn't have axes in bold so its easy to loose count of them when counting. I did the same graph in word and saved it as .png and also .gif, uploaded into templates and changed the existing file name "c2s2p1.gif" into a new one. For some reason I get an error message.  What did I do wrong? 
 webwork-open-problem-library/OpenProblemLibrary/Rochester/setAlgebra16FunctionGraphs/sw4_2_1.pg

**Comment by jwj61** [comment]
It sounds like you did things right, so I can't tell you why things went wrong.  Perhaps giving the error message would help.
