### ISSUE TITLE
round to nearest tenth/hundredth word problem

### ISSUE THREAD

**Issue by ES2660** [openwebwork/webwork-open-problem-library#305]
can someone help me with re-coding this question so that is ask for the answers to the nearest tenth or hundredth  Library/Mizzou/Algebra/eqns_quadratic/quadratic_eqns_app_03.pg

I see that this could probably be applied but i was not able to figure it out:
Context()->flags->set(
  tolerance=>0.002,
  tolType=>"absolute");

**Comment by gajennings** [comment]
In its current form this problem only accepts exact answers e.g. (a+sqrt(b))/c where a, b and c are integers, and the answers must be simplified, so e.g.  (2a+sqrt(4b))/(2c) produces an error message.  The author wrote a lot of complicated code to produce that behavior.  To make it accept inexact decimal answers one would need to remove all that code. To do that, delete lines 97-99 and 119-191, then replace lines 211-242 with these two lines
ANS($base->cmp());
ANS($height->cmp());
Then I think applying the "Context()->flags->..." statement that you suggested should work.
