### ISSUE TITLE
The letter s in math font can be confused with number 8

### ISSUE THREAD

**Issue by lahvak** [openwebwork/webwork-open-problem-library#519]
This particular issue was observed with the problem `Library/Mizzou/Intermediate_Algebra/Rational_and_Radical_Exponents_Simplifying_Radicals/MultiplyRadicals.pg` but I expect the same to happen with any problem where `s` is used for a variable, and the number 8 is not present nearby.
I had a very confused student asking why his obviously correct answer is not accepted.  Unfortunately he did not use the "Email instructor" button, but instead came to my office with a written copy of the problem.  Later when I looked at the problem on the screen, I had to admit that the math italics letter s on a low quality screen indeed looks like it could easily be a number 8, if an actual 8 is not present as well for comparison.
My suggestion is that unless there is a good reason, the variable `s` is avoided in problems.  In this particular problem, the letter is picked randomly from a list, so `s` can easily be avoided.

**Comment by jwj61** [comment]
I removed s as an option on this problem.  I think other problems which use s should be considered on a case by case basis.
