### ISSUE TITLE
Issue with METU-NCC problem

### ISSUE THREAD

**Issue by timkato** [openwebwork/webwork-open-problem-library#533]
https://github.com/openwebwork/webwork-open-problem-library/blob/master/OpenProblemLibrary/METU-NCC/Diff_Eq/2x2-system_soln-cx.pg

In this problem, for parts B and C, we are seeing answers (as inputted by students) getting multiplied by some value such as 6i or 20i depending on the seed.

**Comment by dlglin** [comment]
I can confirm that I get the same behaviour.  For example with the default Library Browser seed (1234?) I get the first entry of parts B and C multiplied by 6i.

You should file a bug in bugzilla, as bugs with individual problems are not actively tracked on GitHub.

**Comment by timkato** [comment]
Thanks. http://bugs.webwork.maa.org/show_bug.cgi?id=4292
