### ISSUE TITLE
Possible problem in UMN library problem

### ISSUE THREAD

**Issue by kcrisman** [openwebwork/webwork-open-problem-library#591]
In webwork-open-problem-library/OpenProblemLibrary/UMN/algebraKaufmannSchwitters/ks_15_5_8.pg I think there may be an error.  (Or maybe I'm reading the problem wrong.)

The problem asks for something like

> A family has 6 children. Assume that each child is as likely to be a boy as it is to be a girl. Find the probability that the family has 6 girls if it is known the family has at least one girl.

Usually such conditional probability problems require an argument of the following nature.

> The conditional probability is the probability of the intersection over the probability of the given.  The intersection is just having 6 girls, which is 1/64 chance; the probability of having at least one girl is the complement to having all boys, which means it is 1-(1/64) or 63/64.  So the conditional probability is 1/63.

However, the answer given seems to be simply the probability of having five girls, which would be 1/32.   Have I misread this problem and what it's asking for?  It does seem to be about conditional probability since the other problems in the WW OPL for that chapter are also about that topic.

I'm happy to try to submit a PR to resolve this if it's agreed the problem is wrong.

**Comment by jwj61** [comment]
I agree that it is a conditional probability and that the current answer is wrong.

**Comment by kcrisman** [comment]
Okay, I'll try to do a PR at some point this week.

**Comment by kcrisman** [comment]
Okay, see #592.
