### ISSUE TITLE
I don't think this problem is correct

### ISSUE THREAD

**Issue by lahvak** [openwebwork/webwork-open-problem-library#601]
` Library/BentleyUniversity/MathematicsOfComputerGraphics/setMoCG-Ch10/10-12-WhereIsAnObjectAtRest.pg`

![problem_error](https://user-images.githubusercontent.com/3579225/65399688-2193b900-dd8c-11e9-8eb3-c9333d6c8de3.png)

As you can see, t=0 is offered as a solution of the system of equations, but cos(0) is not 0.  I do not understand the graph at all.

**Comment by dlglin** [comment]
I’m not sure if this problem can be salvaged.

First off, there appears to be a typo in line 39: $index should be $index1.  At least then the graphs will intersect where the author says they intersect.

The bigger problem is that the author is claiming that the velocity is 0 where the derivatives of the components intersect, which is not the case unless they intersect at a point on the x-axis.

The only easy way I see to fix this is to reduce to the case where the first component of the derivative is sin(t) and the second component is kt for some k, but this trivializes the problem a little.

On Sep 22, 2019, at 8:57 PM, Jan Hlavacek <notifications@github.com<mailto:notifications@github.com>> wrote:


Library/BentleyUniversity/MathematicsOfComputerGraphics/setMoCG-Ch10/10-12-WhereIsAnObjectAtRest.pg

[problem_error]<https://user-images.githubusercontent.com/3579225/65399688-2193b900-dd8c-11e9-8eb3-c9333d6c8de3.png>

As you can see, t=0 is offered as a solution of the system of equations, but cos(0) is not 0. I do not understand the graph at all.

**Comment by jwj61** [comment]
Also, the solution is misleading; both equations are easy to solve.

PGML gives me a headache.  If someone wants to fix this, even if it trivializes the problem, please do so.
