### ISSUE TITLE
I am confused by this problem, there seems to be something missing

### ISSUE THREAD

**Issue by lahvak** [openwebwork/webwork-open-problem-library#623]
The problem on multivariable limits: `Library/MC/Sage/MultiCal/limit_contours_no_formula.pg`
seems to refer to a "worksheet above", but there is no worksheet.  The problem asks to find limits of 6 functions, f_1, ... f_6, but the functions are not defined nor described in any way.  There must be some additional supplementary material that is supposed to be provided with the problem, but in the OPL there is none.  I don't think problems like this belong to the OPL.

In addition, I find the instructions to do polar substitution and take limit as r -> 0 in the solution incorrect, or misleading at best.

**Comment by jwj61** [comment]
I retagged the problem so that it will not show up in the library browser.

**Comment by mgage** [comment]
This problem works for me:  
http://demo.webwork.rochester.edu/webwork2/UR101/sage/7/

I believe that your link to Sage was not working so you don't see the contour map generated by Sage.

**Comment by lahvak** [comment]
I see.  Turns out my browser was blocking javascript from sagemath.org. I am still getting an error for the function f4.  Also, after clicking on the "Click here to evaluate/reload, the content of the sage box disappears and will not come back. I have to reload the page to get it back.
