### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by jirilebl** [openwebwork/webwork-open-problem-library#626]
How does one suggest things that are missing from the Taxonomy?  In some of the problems I've used nonexistant sections in tags, but it'd be nice if they were "official".  Basically they are places where there is no good way to use existing taxonomy.  The list I am missing is the following.  In the last one I've used "Misc." which is used in the library but does not appear in the Taxonomy file.  But it'd be nice to have something there.

In
Differential equations > Partial differential equations
add:
First order equations
Integral transforms

In
Differential equations > Systems of differential equations
add:
Matrix exponential

In
Differential equations > Higher order differential equations
add:
Linear, general

**Comment by jwj61** [comment]
In general, additions to the taxonomy happen when people are reviewing problems for inclusion in the OPL.  It is fine to use your own tags while problems are in contrib.  They might help the person reviewing them to decide if the tags should be added to the Taxonomy at that time, or if the problem belongs in an existing place.
