### ISSUE TITLE
webwork unable to import; mysql error

### ISSUE THREAD

**Issue by bldewolf** [openwebwork/webwork-open-problem-library#64]
Trying to import OPL into webwork using OPL-Update causes this error:

DBD::mysql::st execute failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' at /opt/webwork/webwork2/bin/OPL-update line 290, <IN> line 1097.

This error occurs when handling line 1097 and 1098 of OpenProblemLibrary/Textbooks.  These lines contain extended characters that aren't UTF8, but also aren't valid latin1 characters.

I initially tried changing the database to UTF8 instead of latin1, but this caused course creation to fail (I suppose that should be a separate bug against webwork2).  Next, I changed the symbols to plaintext counterparts ("pi" and "inf").  After this change, the import succeeds.

Ideally, these characters should be changed to their correct UTF8 characters and the database changed to accept UTF8 (perhaps just the columns handling this data?).

**Comment by jwj61** [comment]
I removed the offending characters.  Thanks for pointing it out.
