### ISSUE TITLE
LU decomposition sometimes seems to require upper unitriangular

### ISSUE THREAD

**Issue by kcrisman** [openwebwork/webwork-open-problem-library#666]
In webwork-open-problem-library/OpenProblemLibrary/Rochester/setLinearAlgebra5LUfactorization/ur_la_5_8.pg you can see that the L is apparently required to have 1 on the diagonal, which is not necessarily the definition of LU decomposition.  Lay defines it that way, but neither Nicholson nor Williams nor Wikipedia do, though Williams points out that in a standard algorithm it will be unitriangular and Wikipedia seems to imply this, though its definition does not say so.

In any case, either this requirement should be made very clear, or (preferable to me, but not necessary to close the issue) other LU decompositions should be allowed.

**Comment by jwj61** [comment]
I added wording about 1's on the main diagonal for L.  Others are still welcome to change the answer checker to allow other legal factorizations.

**Comment by kcrisman** [comment]
I added wording about 1's on the main diagonal for L. Others are still
> welcome to change the answer checker to allow other legal factorizations.
>

Thanks!  That's above my skill level with pg right now but I appreciate
this too.
