### ISSUE TITLE
complex numbers give weird error

### ISSUE THREAD

**Issue by kcrisman** [openwebwork/webwork-open-problem-library#739]
In `Library/TCNJ/TCNJ_MatrixLinearTransformation/problem6.pg` with seed 979, if one inputs sqrt(-3) as one of the answers, one gets

> The evaluated answer is not an answer hash : ||.

and

> Use of uninitialized value $new_rh_ans_evaluation_result in concatenation (.) or string at /opt/webwork/pg/lib/WeBWorK/PG/Translator.pm line 1337

I understand that we might not want complex entries in some (many) problems, but in general that doesn't seem to be a problem, such as in `Library/Rochester/setLinearAlgebra3Matrices/ur_la_3_3.pg`.  

Anyway, this error is really confusing to my students, and to me.  Is there a different error mechanism that could be invoked when this sort of input occurs?

**Comment by gajennings** [comment]
I don't see an easy way to fix this.  It's clear from the question that that this problem requires a matrix with real number entries, and sqrt(-3) = (+ or -)i*sqrt(3) isn't even a well-defined complex number.   

The expected answer is a Matrix math object called $A, which must have real number entries.  In the code, the command
$A->ans_array(12)
produces a nice 2x2 array of answer blanks for the student to fill in.  If you replace $A->ans_array(12) with ans_rule() then the problem will emit useful error messages for inputs that are 2x2 matrices with entries like sqrt(-3), but ans_rule() only produces a single answer blank, so the student would have to type a 2x2 matrix answer using "[" and "]" to denote the rows and columns, e.g. [[1,0],[0,1]] for the 2x2 identity matrix.  Something in the ans_array mechanism seems to break when it encounters sqrt(-3).

**Comment by gajennings** [comment]
Replacing Context("Matrix") with Context("Complex-Matrix"), as in the Rochester problem, cures this issue.  I'll fix that in the OPL.

**Comment by kcrisman** [comment]
> Replacing Context("Matrix") with Context("Complex-Matrix"), as in the
> Rochester problem, cures this issue. I'll fix that in the OPL.
>
> Thanks!  By the way, I'm also fine with a complex matrix raising errors -
just that the error it caused was one that doesn't tell the student they
misplaced a minus sign inside instead of outside the square root.  But no
errors is okay too, they still need to get the problem right, not just type
in a legitimate matrix, after all.

**Comment by gajennings** [comment]
I hope students will see the sign error when the answer checker typesets their answer and echoes it back to them.  It would be possible to add some code that checks the matrix to make all the entries are real, and returns an error message if they're not, but it didn't seem necessary.

By the way, thanks for suggesting the comparison with the Rochester problem!  I didn't know about the "Complex-Matrix" context until I saw that.

George Jennings
Math Dept., Calif. State University Dominguez Hills
________________________________
