### ISSUE TITLE
request delete Library/UMass-Amherst/Abstract-Algebra/PS-Relations/Relations5.pg

### ISSUE THREAD

**Issue by gajennings** [openwebwork/webwork-open-problem-library#747]
Please delete
Library/UMass-Amherst/Abstract-Algebra/PS-Relations/Relations5.pg
The expected answer is wrong.  I don't see any way to fix it and turn it into a useful problem.  It confuses the meaning of "symmetric relation" in its solution.

**Comment by jwj61** [comment]
Isn't the right answer any pair (A,B) where A=B?

**Comment by gajennings** [comment]
Yes that's true, my problem was "what's the right question?".  It's fixed now.
