### ISSUE TITLE
request move UMass-Amherst/Abstract-Algebra/PS-RingsIdealsHomomorphisms/RingsIdealsHomomorphisms8.pg

### ISSUE THREAD

**Issue by gajennings** [openwebwork/webwork-open-problem-library#748]
UMass-Amherst/Abstract-Algebra/PS-RingsIdealsHomomorphisms/RingsIdealsHomomorphisms8.pg
should be moved to 
Library/UMass-Amherst/Abstract-Algebra/PS-GroupHomomorphisms
and perhaps renamed because it's really about groups, not rings.  Perhaps you could provide a link from its current location to its new location.  The original problem referred to the quotient "ring" Q/Z, which makes no sense, so I changed it into a problem about groups and changed the tags.  Nevertheless, people who are looking through the problem library could be mislead if they see it in a "rings" directory.

**Comment by jwj61** [comment]
Done
