### ISSUE TITLE
Some problems producing errors

### ISSUE THREAD

**Issue by lozanoj** [openwebwork/webwork-open-problem-library#753]
We're able to pull most problems from the OPL (on Webwork Verf), but there are a few that don't show up and say 

> This problem produced an error.

 We're also getting the same warning message:

> WeBWorK Warnings
WeBWorK has encountered warnings while processing your request. If this occured when viewing a problem, it was likely caused by an error or ambiguity in that problem. Otherwise, it may indicate a problem with the WeBWorK system itself. If you are a student, report these warnings to your professor to have them corrected. If you are a professor, please consult the warning output below for more information.
Warning messages
ERRORS in rendering problem: 5 |Library/NewHampshire/unh_schoolib/Geometry_Figures/gfgbns301.pg| ERRORS from evaluating PG file:
Error detected while loading [PG]/macros/problemPanic.pl:
PG_macro_file_eval detected error at line 124 of file [PG]/lib/PGloadfiles.pm
Malformed UTF-8 character (fatal) at line 1 of (eval 3223), chunk 1.
The calling package is PGloadfiles
Died within PGloadfiles::compile_file called at line 172 of [PG]/lib/PGloadfiles.pm
from within PGloadfiles::loadMacros called at line 581 of [PG]/macros/PG.pl
from within main::loadMacros called at line 2 of (eval 2991)

**Comment by jwj61** [comment]
It looks like this problem loads the macro file problemPanic.pl, and that is the file causing the problem.  Presumably, that file contains a character which is "Malformed UTF-8".  As such, it would be an issue for the pg part of webwork, not for the OPL.

**Comment by lozanoj** [comment]
Okay, thanks!
