### ISSUE TITLE
Unicode in PopUp menu causing errors

### ISSUE THREAD

**Issue by lahvak** [openwebwork/webwork-open-problem-library#817]
The following problems:

*  `Library/Mizzou/Finite_Math/Linear_Programming_Inequalities_in_two_variables/Ineq1.pg`
*  `Library/Mizzou/Finite_Math/Linear_Programming_Inequalities_in_two_variables/ShadedIneq1.pg`
*  `Library/Mizzou/Finite_Math/Linear_Programming_Inequalities_in_two_variables/SystemFilled1.pg`

use unicode inequality signs in a PopUp menu, which seems to be causing errors like this:

```
DBD::mysql::st execute failed: Incorrect string value: '\xE2\x89\xA4\x094' for column `webwork`.`Math145-Wi21-JHlavacek_past_answer`.`answer_string` at row 1 at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 837.
```

What's interesting/annoying is that this error will only show when __submitting__ an answer in an open set, it will not happen when previewing or testing the problem in a closed set.

This is in WW 2.15.  Perhaps openwebwork/pg#518 fixes it?

I think it is a library issue rather than a pg issue, since it has been mentioned repeatedly that unicode should not be used in popup menus (although with luatex or xetex it should work fine in a hardcopy?)

**Comment by dlglin** [comment]
Was the course where you are seeing this created in 2.15, or was it created in a previous version and then upgraded?

**Comment by lahvak** [comment]
It was created in 2.15.

**Comment by gajennings** [comment]
Replaced unicode inequality symbols with "<=" and ">=".
