### ISSUE TITLE
Previous commit made a problem confusing

### ISSUE THREAD

**Issue by lahvak** [openwebwork/webwork-open-problem-library#818]
The commit 7ec25ce77ef5c00413c7fd48a5d651ff9e7f3ff7 fixed previous bug but left the text of the problem confusing: the text asks for an antiderivative of a function, and provides an answer blank, __followed by '+ C'__.  After the commit, the answer is evaluated using `FormulaUpToConstant` so it requires students to _also enter '+C' in their answer_, so that '+C' will be present twice. Possible fixes:

* Remove the '+C' from the text of the problem.  In that case some instructions like "enter the indefinite integral in the most general form" should probably be provided,
* Keep the '+C' in the text, and use regular `Formula` for the answer, with `ANS($ans->cmp(upToConstant=>1));` as the answer evaluator.

**Comment by gajennings** [comment]
Fixed.  Please report bugs to webwork's bugzilla https://bugs.webwork.maa.org
