### ISSUE TITLE
Problem opening homework set editor in a course with 2 symbolic links to /opt/webwork/libraries/webwork-open-problem-library/OpenProblemLibrary in a course template directory (with a recent OPL)

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork-open-problem-library#862]
A few days ago commit https://github.com/openwebwork/webwork-open-problem-library/commit/a8d13d147de41ac5ed1aa0e0b6aeba74ab5e051e added a symbolic link called `OpenProblemLibrary` in the `OpenProblemLibrary` directory.

I'm not certain why such a link would be needed, but under certain circumstances the addition of the new link makes problems.

When this link exists, a course which has 2 symbolic links to `/opt/webwork/libraries/webwork-open-problem-library/OpenProblemLibrary` in the a course template directory will not allow instructors to open the homework set editor and instead reports an error. (See below.) It seems that someone in the course where this was discovered wanted to allow typing "library" all in lowercase sometimes.

Deleting **either** the `OpenProblemLibrary` symbolic link in the `OpenProblemLibrary` directory **or** the second symbolic link to `OpenProblemLibrary` in the course template directory fixes the problem.

@gajennings - Was the link added intentionally? If not, could it be `git rm` removed?

---

My Apache `error.log` file had a line (somewhat edited):
[Mon Aug 09 04:49:30.100757 2021] [perl:error] [pid 74172] [client IP_HIDEDEN:51232] {"Backtrace":["in File::Find::Follow_SymLink called at line 638 of /usr/share/perl/5.30/File/Find.pm","in File::Find::_find_dir_symlnk called at line 224 of /usr/share/perl/5.30/File/Find.pm","in File::Find::_find_opt called at line 760 of /usr/share/perl/5.30/File/Find.pm","in File::Find::find called at line 700 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor.pm","in WeBWorK::ContentGenerator::Instructor::getDefList called at line 1275 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList.pm","in WeBWorK::ContentGenerator::Instructor::ProblemSetList::import_form called at line 596 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList.pm","in WeBWorK::ContentGenerator::Instructor::ProblemSetList::body called at line 155 of /opt/webwork/webwork2/lib/WeBWorK/Template.pm","in WeBWorK::Template::template called at line 621 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm","in WeBWorK::ContentGenerator::content called at line 232 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm","in WeBWorK::ContentGenerator::go called at line 386 of /opt/webwork/webwork2/lib/WeBWorK.pm"],"Warnings":[],"Time":"Mon Aug 09 04:49:30 2021","HTTP Headers":{"Accept-Language":"en-US,en;q=0.5","Cookie":"REMOVED","Sec-Fetch-Mode":"navigate","Sec-Fetch-Site":"same-origin","Sec-Fetch-Dest":"document","Sec-Fetch-User":"?1","Referer":"https://webwork.technion.ac.il/webwork2/COURSE_NAME_REMOVED/","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","User-Agent":"REMOVED","Connection":"keep-alive","Accept-Encoding":"gzip, deflate, br","Upgrade-Insecure-Requests":"1","Host":"webwork.technion.ac.il"},"Method":"GET","URI":"/webwork2/COURSE_NAME_REMOVED/instructor/sets/","Error record identifier":"4449c1dc-ba1d-5352-8ad5-c068b6a7b553::096eef45-f8b4-11eb-baaa-f06cfcf8c60a","Exception":"/opt/webwork/libraries/webwork-open-problem-library/OpenProblemLibrary/OpenProblemLibrary is encountered a second time at /usr/share/perl/5.30/File/Find.pm line 79."}, referer: https://webwork.technion.ac.il/webwork2/COURSE_NAME_REMOVED/
```

**Comment by taniwallach** [comment]
Note: The problem is triggered by any symbolic link in the `/opt/webwork/libraries/webwork-open-problem-library/OpenProblemLibrary` directory when there are 2 links to there in the course templates directory. The error message will list the name of the symbolic link in that directory.

---

The error stack-trace more nicely formatted (pulled from a WW 2.15 server where it is sent in the HTML and not just logged):

```
Error messages
/opt/webwork/libraries/webwork-open-problem-library/OpenProblemLibrary/OpenProblemLibrary is encountered a second time at /usr/share/perl/5.30/File/Find.pm line 79.
Call stack
The information below can help locate the source of the problem.

in File::Find::Follow_SymLink called at line 638 of /usr/share/perl/5.30/File/Find.pm
in File::Find::_find_dir_symlnk called at line 224 of /usr/share/perl/5.30/File/Find.pm
in File::Find::_find_opt called at line 760 of /usr/share/perl/5.30/File/Find.pm
in File::Find::find called at line 700 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor.pm
in WeBWorK::ContentGenerator::Instructor::getDefList called at line 1311 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList2.pm
in WeBWorK::ContentGenerator::Instructor::ProblemSetList2::import_form called at line 593 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList2.pm
in WeBWorK::ContentGenerator::Instructor::ProblemSetList2::body called at line 155 of /opt/webwork/webwork2/lib/WeBWorK/Template.pm
in WeBWorK::Template::template called at line 611 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::content called at line 233 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::go called at line 478 of /opt/webwork/webwork2/lib/WeBWorK.pm
```

**Comment by gajennings** [comment]
That was a "fat fingers" error.  It's gone now.

**Comment by taniwallach** [comment]
Thanks!
