### ISSUE TITLE
Problem gives a score of 0 in quizzes, but works fine in homework sets.

### ISSUE THREAD

**Issue by ionparticle** [openwebwork/webwork-open-problem-library#927]
This is a weird one.

Problem in question: https://github.com/openwebwork/webwork-open-problem-library/blob/main/OpenProblemLibrary/Rochester/setSeries6CompTests/ur_sr_6_10a.pg

If you use it in a quiz, everyone gets a problem score of 0, even if they answered everything correctly. Using it in a regular homework set works fine.

Screenshot of quiz giving a score of 0 even though everything is correct:
![issue in quiz](https://user-images.githubusercontent.com/1386330/164337896-71805021-9e2e-4cec-8dbe-a5fcfb756448.png)

For comparison, screenshot of it working fine in a homework set:
![no issue in homework set](https://user-images.githubusercontent.com/1386330/164336665-d724d597-3579-45c2-8f92-f787d7872f04.png)

**Comment by drdrew42** [comment]
The issue is that the response fields are hard-coded as `AnSwEr000n`, which is not consistent when used in the gateway setting. Gateway assignments prepend a prefix in order to allow for multiple problems to be displayed on the same page -- keeping answers from different problems separate. When this happens, the custom answer grader in this problem looks in the 'wrong' place for the scores for each answer blank. I have a few ideas about how to retain the functionality of this problem while also fixing this flaw, I'll make a PR and tag you once that is completed.

**Comment by drdrew42** [comment]
It seems that this technique has been used in several problems throughout the OPL, and they would all be affected in a similar manner. 

@ionparticle -- If you confirm that this fix works for you, then I'll work on applying the same fix to the other affected problems.

**Comment by ionparticle** [comment]
@drdrew42 thanks for the quick work! Unfortunately, it's still giving me a score of 0 in the quiz, the new message `This attempt scored 100%. Nice work.` did show up though.

First question is the old version, second question is the new version, third question is a sanity check just to make sure score recording is working:
![issue in quiz 2](https://user-images.githubusercontent.com/1386330/164548406-fce2f015-e9b5-48ae-b485-1bcb7c9e824b.png)

**Comment by drdrew42** [comment]
@ionparticle thanks for trying that out -- I made a silly mistake that I overlooked because the message displayed what I wanted it to. The latest change should give us the fix that we're after.

**Comment by ionparticle** [comment]
@drdrew42 that fixes it! Thanks for your work!

It is now giving the proper score in quizzes (tested 100%, 50%, 0%), it also still works in a homework set.

**Comment by drdrew42** [comment]
And thank you for raising the issue -- I'm going to start digging through the OPL to resolve similar issues.
```
./maCalcDB/setIntegrationProjects/proj0/proj0h.html
./maCalcDB/setSampleQuestionnaires/TA_evaluation/TA_evaluation_fall02.html
./maCalcDB/setSampleQuestionnaires/WeBWorK_evaluation/WeBWorK_questionnaire_fall02.html
./maCalcDB/setDerivatives21LHospital/osu_dr_21_20.pg
./maCalcDB/setSampleGraders/sample_myown_grader.html
./MC/Sage/LinearAlg/Axb_span.pg
./Utah/Calculus_II/set8_Infinite_Series/set8_pr18.pg
./Utah/Calculus_II/set7_Infinite_Series/set7_pr15.pg
./CSUOhio/appletDemonstrationProblems/graphLimits3.pg
./CSUOhio/appletDemonstrationProblems/graphLimits2.pg
./CSUOhio/appletDemonstrationProblems/graphLimits.pg
./ASU-topics/setLogarithmicFunctions/di3.pg
./ASU-topics/setCalculus/stef/stef4_4p1.pg
./ASU-topics/set119LinearSystems/p12.pg
./ASU-topics/set119LinearSystems/p32.pg
./ASU-topics/set119LinearSystems/p2.pg
./ASU-topics/set119LinearSystems/p6.pg
./ASU-topics/set119LinearSystems/p1.pg
./ASU-topics/set119LinearSystems/p4.pg
./ASU-topics/set119LinearSystems/p20.pg
./ASU-topics/set119LinearSystems/p24.pg
./ASU-topics/set119LinearSystems/p10.pg
./ASU-topics/set119LinearSystems/p31.pg
./ASU-topics/setExponentialFunctions/jj1.pg
./Indiana/Indiana_setSeries5IntegralTest/ur_sr_5_11.pg
./Rochester/setIntegrationProjects/proj0/proj0h.html
./Rochester/setSampleQuestionaires/TA_evaluation/TA_evaluation_fall02.html
./Rochester/setSampleQuestionaires/WeBWorK_evaluation/WeBWorK_questionnaire_fall02.html
./Rochester/setSeries6CompTests/benny_ser3B.pg
./Rochester/setSeries6CompTests/benny_ser2b.pg
./Rochester/setSeries6CompTests/ur_sr_6_9a.pg
./Rochester/setSeries6CompTests/benny_ser4B.pg
./Rochester/setSeries6CompTests/ur_sr_6_10a.pg
./Rochester/setSeries3Convergent/ns8_3_7BB.pg
./Rochester/setSeries3Convergent/ns8_3_17BB.pg
./Rochester/setDerivatives21LHospital/osu_dr_21_20.pg
./Rochester/setSeries7AbsolutelyConvergent/eva8_4aBB.pg
./Rochester/setSeries7AbsolutelyConvergent/ns8_4_20BB.pg
./Rochester/setSeries7AbsolutelyConvergent/eva8_3_2BB.pg
./Rochester/setSampleGraders/sample_myown_grader.pg
./Rochester/setSampleGraders/sample_myown_grader.html
```
